name: Convert Markdown to PDF

on:
  push:
    paths:
      - CV.md
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
    - name: Download CV.md
      run: |
        curl -L -o CV.md https://raw.githubusercontent.com/Jouffluu/CV/main/CV.md
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-latex-base texlive-xcolor
        
    - name: Convert Markdown to PDF
      run: |
        pandoc CV.md -o CV.pdf
        
    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: CV-pdf
        path: CV.pdf
